docs_dir: site
site_dir: docs

site_name: Observant.py
site_url: https://mrowrlib.github.io/observant.py
site_description: Reactive state management for Python
site_author: Mrowr Purr

repo_url: https://github.com/MrowrLib/observant.py
repo_name: MrowrLib/observant.py

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables

extra_css:
  - style.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Documentation:
      - Core Types: reference/all_types.md
      - Observable: reference/observable.md
      - Observable List: reference/observable_list.md
      - Observable Dictionary: reference/observable_dict.md
      - Observable Proxy:
          - Overview: reference/proxy/index.md
          - Validation: reference/proxy/validation.md
          - Undo/Redo: reference/proxy/undo.md
          - Computed Fields: reference/proxy/computed.md
          - Syncing & Dirty State: reference/proxy/sync.md
  - Examples:
      - Basic Usage: examples/basic.md
      - Advanced Patterns: examples/advanced.md
  - API Reference:
      - Overview: api_reference/index.md
      - Observable: api_reference/observable.md
      - ObservableDict: api_reference/observable_dict.md
      - ObservableList: api_reference/observable_list.md
      - ObservableProxy: api_reference/observable_proxy.md
      - UndoableObservable: api_reference/undoable_observable.md
      - Interfaces:
          - Overview: api_reference/interfaces/index.md
          - IObservable: api_reference/interfaces/iobservable.md
          - IObservableList: api_reference/interfaces/iobservable_list.md
          - IObservableDict: api_reference/interfaces/iobservable_dict.md
          - IObservableProxy: api_reference/interfaces/iobservable_proxy.md
      - Types:
          - Overview: api_reference/types/index.md
          - ObservableCollectionChangeType: api_reference/types/observablecollectionchangetype.md
          - ObservableListChange: api_reference/types/observablelistchange.md
          - ObservableDictChange: api_reference/types/observabledictchange.md
          - ProxyFieldKey: api_reference/types/proxyfieldkey.md
          - UndoConfig: api_reference/types/undoconfig.md
