docs_dir: site
site_dir: docs

site_name: Observant.py
site_url: https://mrowrlib.github.io/observant.py
site_description: Reactive state management for Python
site_author: Mrowr Purr

repo_url: https://github.com/MrowrLib/observant.py
repo_name: MrowrLib/observant.py

theme:
  name: material
  favicon: favicon.ico
  palette:
    
    # Palette toggle for light mode
    - scheme: 
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-7 # (2)!
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables

extra_css:
  - style.css

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            show_root_heading: true
            heading_level: 2

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Features:
      - Change Tracking: features/change_tracking.md
      - Validation: features/validation.md
      - Undo and Redo: features/undo.md
      - Computed Properties: features/computed.md
      - Dirty Tracking: features/dirty.md
      - Sync vs Non-Sync: features/sync.md
      - Saving and Loading: features/save_load.md
  - API Reference: api_reference/index.md
