site_name: Observant.py
site_url: https://mrowrlib.github.io/observant.py

theme:
  name: material

extra_css:
- style.css

plugins:
- search
- mkdocstrings

nav:
- index.md
- Code Reference: reference.md